/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GovernmentAerospaceRouteImport } from './routes/government-aerospace'
import { Route as IndexRouteImport } from './routes/index'

const GovernmentAerospaceRoute = GovernmentAerospaceRouteImport.update({
  id: '/government-aerospace',
  path: '/government-aerospace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/government-aerospace': typeof GovernmentAerospaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/government-aerospace': typeof GovernmentAerospaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/government-aerospace': typeof GovernmentAerospaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/government-aerospace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/government-aerospace'
  id: '__root__' | '/' | '/government-aerospace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GovernmentAerospaceRoute: typeof GovernmentAerospaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/government-aerospace': {
      id: '/government-aerospace'
      path: '/government-aerospace'
      fullPath: '/government-aerospace'
      preLoaderRoute: typeof GovernmentAerospaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GovernmentAerospaceRoute: GovernmentAerospaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
